<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AboutUS.aspx.cs" Inherits="GYM_4._1.AboutUS" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>About Us</title>
    <!-- main css and js file -->
    <link href="Boostrap/css/bootstrap.min.css" rel="stylesheet" />
    <style type="text/css">
        .auto-style2 {
            width: 55px;
        }
        .auto-style3 {
            width: 1695px;
        }
    </style>
</head>
<body >
    <form id="form1" runat="server">
        <div>
            <h1 align="center">About Us</h1><br /><br />
            <div align="center"><asp:Image ID="Image1" ImageAlign="Middle" runat="server" ImageUrl="~/Stock/ad.jpg" Height="480px" Width="1400px" /></div>

            <div align="center">

                <table class="w-100">
                    
                    <tr>
                        
                        <td class="auto-style3" >
                            <h1 align="center" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(0, 0, 0); font-weight: normal; line-height: 1.3; font-size: 1.8rem; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Sonawane's The Gym</h1>
                            <br style="box-sizing: border-box; margin: 0px; color: rgba(0, 0, 0, 0.6); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
                            
                            <p align="justify" style="box-sizing: border-box; margin: 0px 0px 5px; font-size: medium; line-height: 28px; color: rgba(0, 0, 0, 0.6); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                                <span style="color: rgb(38, 38, 38); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 600; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Sonawane&#39;s The Gym</span> is established in the year 2018. At 
                                <span style="color: rgb(38, 38, 38); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 600; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Sonawane&#39;s The Gym</span> our goal is to assist you in reaching your fitness and nutritional goals. Our job is to provide safe and effective exercises that will enable you to lose those unwanted pounds, gain muscle tone and simply improve your overall appearance and health. Your job is to commit to making exercise and good nutrition a priority in order to achieve success. By working together on changing the way you think and feel about fitness and nutrition, we can help you not only transform your body, but also transform your life!<br style="box-sizing: border-box; margin: 0px;" />
                                <br style="box-sizing: border-box; margin: 0px;" />
                                We follow a globally proven fitness training module with state-of-the-art infrastructure and delivery methodology and continuous upgradation through training programs. With certified trainers and nutritional counseling, Sonawane's The Gym provides a comprehensive approach to the health and wellness of its members.<br style="box-sizing: border-box; margin: 0px;" />
                                <br style="box-sizing: border-box; margin: 0px;" />
                                Our main workout area is spacious, allowing plenty of room to exercise safely. Our equipment is JERAI designed machine, which is one of the best Indian Brand. There is a wide selection of training equipment whatever you need. Our circuit area houses our functional training frame work. You can perform numerous body weight exercises.<br style="box-sizing: border-box; margin: 0px;" />
                                <br style="box-sizing: border-box; margin: 0px;" />
                                We have a very talented, young, energetic and strong team of certified trainers with a collective Industry experience of over 25 years.</p>
                            <br style="box-sizing: border-box; margin: 0px; color: rgba(0, 0, 0, 0.6); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
                            <br style="box-sizing: border-box; margin: 0px; color: rgba(0, 0, 0, 0.6); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
                            <h1 align="center" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(0, 0, 0); font-weight: normal; line-height: 1.3; font-size: 1.8rem; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Objectives</h1>
                            <br style="box-sizing: border-box; margin: 0px; color: rgba(0, 0, 0, 0.6); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
                            <p align="justify" style="box-sizing: border-box; margin: 0px 0px 5px; font-size: medium; line-height: 28px; color: rgba(0, 0, 0, 0.6); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                                The company&#39;s objective is to build a quality, full-service facility that will command the approval of the local community which it serves.<br style="box-sizing: border-box; margin: 0px;" />
                                <br style="box-sizing: border-box; margin: 0px;" />
                                Our goals include:<br style="box-sizing: border-box; margin: 0px;" />
                                1. A major market share in local market.<br style="box-sizing: border-box; margin: 0px;" />
                                2. An increase in our gross margins.<br style="box-sizing: border-box; margin: 0px;" />
                                3. Maintain and grow our position as one of the only Fitness hub in Nallasopara area that caters to it’s clients.</p>
                            <br style="box-sizing: border-box; margin: 0px; color: rgba(0, 0, 0, 0.6); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
                            <br style="box-sizing: border-box; margin: 0px; color: rgba(0, 0, 0, 0.6); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
                            <h1 align="center" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(0, 0, 0); font-weight: normal; line-height: 1.3; font-size: 1.8rem; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Mission</h1>
                            <br style="box-sizing: border-box; margin: 0px; color: rgba(0, 0, 0, 0.6); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
                            <p align="justify" style="box-sizing: border-box; margin: 0px 0px 5px; font-size: medium; line-height: 28px; color: rgba(0, 0, 0, 0.6); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                                At Sonawane's The Gym our goal is to assist you in reaching your fitness and nutritional goals. Our job is to provide safe and effective exercises that will enable you to lose those unwanted pounds, gain muscle tone and simply improve your overall appearance and health. Your job is to commit to making exercise and good nutrition a priority in order to achieve success. By working together on changing the way you think and feel about fitness and nutrition, we can help you not only transform your body, but also transform your life!</p>
                            <br style="box-sizing: border-box; margin: 0px; color: rgba(0, 0, 0, 0.6); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
                            <br style="box-sizing: border-box; margin: 0px; color: rgba(0, 0, 0, 0.6); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
                            <h1 align="center" style="box-sizing: border-box; margin: 0px 0px 15px; color: rgb(0, 0, 0); font-weight: normal; line-height: 1.3; font-size: 1.8rem; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Keys to Success</h1>
                            <br style="box-sizing: border-box; margin: 0px; color: rgba(0, 0, 0, 0.6); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
                            <p align="justify" style="box-sizing: border-box; margin: 0px 0px 5px; font-size: medium; line-height: 28px; color: rgba(0, 0, 0, 0.6); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                                Keys to success for the company will include:<br style="box-sizing: border-box; margin: 0px;" />
                                <br style="box-sizing: border-box; margin: 0px;" />
                                1. Maintaining a reputable and untarnished reputation in the community.<br style="box-sizing: border-box; margin: 0px;" />
                                2. Strong, Quality, Dynamic, well known, good market presence and Award winning brand equipments.<br style="box-sizing: border-box; margin: 0px;" />
                                3. Quality service<br style="box-sizing: border-box; margin: 0px;" />
                                4. Competitive / economic pricing.<br style="box-sizing: border-box; margin: 0px;" />
                                5. Flexible hours.</p>
                        </td>
                    </tr>
                    
                </table>

            </div>
        </div>
    </form>
</body>
</html>
